import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link style={{width:"500px",background:"red"}} href={"/post"}>post</Link>
          <Link  style={{width:"500px",margin:"20px",background:"green"}} href={"/art"}>art</Link>
          <Link  style={{width:"500px",background:"blue"}} href={"/art/story"}>story</Link>
        </nav>
        
        <div >{children}</div>
        
        </body>
    </html>
  );
}
